/// Flutter icons FastTrackIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FastTrackIcons
///      fonts:
///       - asset: fonts/FastTrackIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FastTrackIcons {
  FastTrackIcons._();

  static const _kFontFam = 'FastTrackIcons';

  static const IconData fasting = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData journal = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe802, fontFamily: _kFontFam);
}
